config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  root 'resources#index'
  get 'home', to: 'static_pages#home'
  get 'cssrule', to: 'static_pages#cssrule'
  get 'static_pages/test'
  resources :resources
  devise_scope :admin do
		get '/admin' => 'devise/sessions#new'
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_many :resources
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :resources
end

app/models/resource.rb
class Resource < ApplicationRecord
	belongs_to :admin
	belongs_to :category

	def self.search(search)
	  if search
			if Rails.env.development?
		    where("LOWER(title) LIKE ?", "%#{search.downcase}%")
		  else
		    where("LOWER(title) ILIKE ?", "%#{search}%")
		  end 
	  else
	    unscoped
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  before_action :set_resource, only: [:show, :edit, :update, :destroy]
  # GET /resources
  # GET /resources.json
  def index
    @admin = current_admin
    @categories = Category.all.map { |c| [c.category, c.id] }
    if params[:category].blank?
      @resources = Resource.search(params[:search]).order("created_at DESC").paginate(:per_page => 8, :page => params[:page])
    else
      filter_categories
    end
    gon.new_variable = Resource.all.order("created_at DESC")
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end
  def select_resources
    @resources = Resource.all
    render "resources", :resources => @resources
  end

  # GET /resources/new
  def new
    @resource = current_admin.resources.build
    @categories = Category.all.map { |c| [c.category, c.id] }
  end

  # GET /resources/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.category, c.id] }
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = current_admin.resources.build(resource_params)
    if params[:category_id].empty? 
      @resource.category_id = 1
    else
      @resource.category_id = params[:category_id]
    end
    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    if params[:category_id].empty? 
      @resource.category_id = 1
    else
      @resource.category_id = params[:category_id]
    end
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:title, :description, :link, :category_id)
    end

    def filter_categories
      @category_id = Category.find_by(category: params[:category]).id
      @resources = Resource.where(category_id: @category_id).order("created_at DESC").paginate(:per_page => 8, :page => params[:page])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def cssrule
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if admin_signed_in? %>
<%= link_to 'New Category', new_category_path %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Canape Pack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= Gon::Base.render_data %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
      <div id="v-for-resources">
      <%= render 'shared/header' %>
      <section class="b-main-content-wrapper">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
               <%= yield %>
            </div>
          </div>
        </div>
      </section>
      <%= render 'shared/footer' %>
      </div>
      <%= javascript_include_tag 'application','jquery', 'data-turbolinks-track' => true  %>
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
  </div>
  <br>
  <div class="field">
    <%= form.label :title, 'Название. По этому параметру идет поиск.'  %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description, 'Описание. Чем короче, тем лучше.' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :link, 'Абсолютный путь до ресурса.' %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/resources/_resources.html.erb
<div id="resources-rails" class="b-resources">
  <div class="row">
     <% @resources.each_with_index do |resource, i| %>
      <div class="resources__card col-lg-4 col-md-6 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to resource.title, resource.link %></h5>
            <p class="card-text"><%= resource.description %></p>
            <a href="<%= resource.link %>" class="btn btn-primary"><i class="fas fa-fire"></i> Погнали!</a>
            <span id="resource<%= i %>" style="display: none;"><%= resource.link %></span>
            <button onClick="copyToClipboard('#resource<%= i %>')" class="btn btn-success">Скопировать</button>
            <% if admin_signed_in? %>
              <div class="resources__adminlinks">
                <%= link_to 'Show', resource, class: "btn btn-primary" %>
                <%= link_to 'Edit', edit_resource_path(resource), class: "btn btn-primary" %>
                <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div> 

<div class="b-resources">
  <div class="row profile">

   <div class="resources__card col-lg-4 col-md-6 col-sm-12" v-for="resource in filteredResources">
    
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><a :href="resource.link">{{ resource.title }}</a></h5>
          <p class="card-text">{{ resource.description }}</p>
          <a :href="resource.link" class="btn btn-primary"><i class="fas fa-fire"></i> Погнали!</a>
          <span :id="'resource' + resource.id + '1'" style="display: none;">{{ resource.link }}</span>
          <button :id="'resource' + resource.id" v-on:click="copyToClipboard($event)" class="btn btn-success">Скопировать</button>
          <% if admin_signed_in? %>
            <div class="resources__adminlinks">
              <a :href="'resource/' + resource.id" class="btn btn-primary">Show</a>
              <a :href="'resource/' + resource.id + '/edit'" class="btn btn-primary">Edit</a>
              <a data-confirm="Are you sure?" rel="nofollow" data-method="delete" :href="'/resources/' + resource.id" class="btn btn-danger">Destroy</a>
            </div>
          <% end %>
        </div>
      </div>

    </div>

  </div>
</div>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @resources, renderer: BootstrapPagination::Rails %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>
<% if @resources.empty? %>
	<h2>К сожалению, ресурсов с таким названием сейчас нет.</h2>

	<% if admin_signed_in? %>
		<h2>Но вы можете:</h2>
		<%= link_to 'Добавить ресурс', new_resource_path, class: "btn btn-info" %>
	<% end %>
<% else %>
	<h1>Ресурсы</h1>
	<% if !params[:category].nil? %>
	<h2 class="current-category">Категория: <%= params[:category] %></h2>
	<% end %>
	<div id="resources"><%= render 'resources' %></div>
	<br>
	<% if admin_signed_in? %>
		<%= link_to 'Добавить ресурс', new_resource_path, class: "btn btn-info" %>
	<% end %>
<% end %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @resource.link %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/shared/_footer.html.erb
<footer class="b-footer">
    <div class="container">
        <div class="footer__row">
            <div class="footer__copyright col-lg-12">
                WebCanape - <a href="https://www.web-canape.ru/?utm_source=copyright">создание сайтов</a> и <a href="https://www.web-canape.ru/seo/?utm_source=copyright">продвижение</a>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<div class="b-header">
  

<div class="container">
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= resources_path %>">Ресурсы</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категории
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Category.all.each do |c| %>
            <%= link_to c.category, resources_path(category: c.category), class: "#{ 'active' if params[:category] == c.category } dropdown-item" %>
          <% end %>
          <% if admin_signed_in? %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Добавить категорию', new_category_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Поиск по категориям', categories_path, class: 'dropdown-item'  %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Полезности
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'CSS правило', cssrule_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">Че-нибудь еще?</a>
        </div>
      </li>
     <% if current_admin %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Админка
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Выйти', destroy_admin_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
      <%= form_tag resources_path, :method => 'get', :id => "resources_search", class: "form-inline" do %>
        <% if current_page?(root_path) || current_page?(resources_path) %>
          <input id="search" type="text" name="search" v-model="search" class='form-control mr-sm-2' >
        <% else %>
          <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
        <% end %>
        <%= submit_tag "Поиск", :name => nil, class: "btn btn-success btn-outline-success my-2 my-sm-0" %>
      <% end %>
 
  </div>
</nav> 
</div>

</div>


app/views/static_pages/cssrule.html.erb
<h1>Правило для написания CSS-стилей</h1>
<pre>
.class {

    /*- отступы -*/
    padding: 0;
    margin: 0;
    border: 1px solid #000;
    border-radius: 0;

    /*- box model -*/
    display: inline-block;
    vertical-align: middle;
    width: 100%;
    height: auto;
    box-sizing: border-box;
    visibility: hidden;

    -webkit-flex: none;
    flex: none;
    -webkit-flex-flow: row wrap;
    flex-flow: row wrap;

    /*- позиция -*/
    position: absolute;
    top: 0;
    right: 0;
    z-index: 999;
    
    /*- декорация -*/
    background-color: #fff;
    opacity: .75;

    /*- типографика -*/
    font-size: 14px;
    font-weight: bold;
    font-family: "Arial", sans-serif /* бязательно указывать fallback для семейств*/;
    text-transform: uppercase;
    text-decoration: none;
    text-align: center;
    color: #000;

    /*- трансформации -*/
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    transform: rotate(45deg);

    /*- анимации -*/
    -webkit-transition: opacity .3s linear;
    -o-transition: opacity .3s linear;
    transition: opacity .3s linear;

    /*- etc -*/
    cursor: pointer;
}	
</pre>

app/views/static_pages/home.html.erb
<% if admin_signed_in? %>

	<h1>Здесь, типа, эээ, самые крутые ресурсы для верстки.</h1>
	<ul>
		<li><%= link_to 'Ресурсы', resources_path %></li>
		<li><%= link_to 'Добавить ресурс', new_resource_path %></li>
		<li><%= link_to 'CSS правило', cssrule_path %></li>
		<li><%= link_to 'Выйти', destroy_admin_session_path, method: :delete %></li>
	</ul>
<% else %>

<% end %>

app/views/static_pages/test.html.erb
<h1>StaticPages#test</h1>
<p>Find me in app/views/static_pages/test.html.erb</p>